Feature/wp categories rm
DenisseC02/WordPress_ApiTesting pull request #13
Opened 2023-04-19 22:13 UTC by Rochius

Hi! Here is the file with the categories keywords for the CRUD, also a file with a name generator

2023-04-20 05:23 UTC, MartinJAA requested changes

2023-04-20 05:23 UTC, MartinJAA commented on wp_api/keywords/categories/categories_keywords.robot
Hi @Rochius, please follow this convention in order to distinguish them:
Keyword: Create New Post
Python method: create_new_post
And add a line at the end of your file, please.

2023-04-21 03:30 UTC, MartinJAA requested changes

2023-04-21 03:30 UTC, MartinJAA commented on wp_api/resources/imports.robot
Please fix the indentation, must be the same for all Libraries

2023-04-21 03:30 UTC, MartinJAA commented on wp_api/tests/categories/tb78_categories.robot
Please add a line a the ned of the file

2023-04-21 03:42 UTC, Rochius commented on wp_api/resources/imports.robot
I already made the changes. Thank you!!

2023-04-21 03:44 UTC, Rochius commented on wp_api/tests/categories/tb78_categories.robot
I already made the changes. Thank you!!

2023-04-21 03:45 UTC, MartinJAA approved these changes

2023-04-21 05:02 UTC, Rogerrenjifo reviewed
Good job my friend Just please remove config.py.

2023-04-21 13:16 UTC, Rogerrenjifo approved these changes
LGTM my friend.

2023-04-21 13:17 UTC, merged